version: '3.8'

services:
  db:
    image: postgres:15
    container_name: temperature-sensor-db
    environment:
      POSTGRES_DB: temperature-sensor
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
